USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/bbk/playx/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := 
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := boot.img

BOARD_KERNEL_CMDLINE := no_console_suspend
BOARD_KERNEL_BASE := 0x802000000
BOARD_KERNEL_PAGESIZE := 00000800 

#BOARD_KERNEL_PAGESIZE := 2048 bytes

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/bbk/playx/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
